#https://www.spigotmc.org/wiki/plugin-yml/
name: Step_0
version: 1.0.0
main: org.saabye_pedersen.mc.Main
author: Kim
description: Step 0
api-version: 1.20
commands:
  sheepdog:
    description: Heard some sheep
    usage: /<command>
